

worker_processes  1;



events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;


    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    # 开启gzip压缩，同理，关闭为off
    gzip on;
    # 压缩的级别，一般取2-6，级别越高，压缩的越小，但越耗费服务器的cpu
    gzip_comp_level 6;
    # 超过1K的文件才进行压缩
    gzip_min_length 1k;
    # 文件类型
    gzip_types image/png image/jpeg image/gif image/svg+xml text/plain application/javascript text/css;
    # 在响应头中添加 Vary
    gzip_vary on;

    server {
        # nginx 监听端口
        listen       80;
        # 服务器ip
        server_name  localhost;

        location / {
            # 前端资源存放路径
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}
